// <auto-generated />
using System;
using Litigations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Litigations.Data.Migrations
{
    [DbContext(typeof(LitigationsDbContext))]
    [Migration("20260928200236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Litigations.Models.Litigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CivilId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("civil_id");

                    b.Property<string>("CourtCaseNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("court_case_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("FiledDate")
                        .HasColumnType("date")
                        .HasColumnName("filed_date");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("VerdictDate")
                        .HasColumnType("date")
                        .HasColumnName("verdict_date");

                    b.HasKey("Id")
                        .HasName("pk_litigations");

                    b.HasIndex("CivilId")
                        .HasDatabaseName("ix_litigations_civil_id");

                    b.HasIndex(new[] { "CourtCaseNumber", "LoanId" }, "ix_litigations_court_case_number_loan_id")
                        .IsUnique()
                        .HasDatabaseName("ix_litigations_court_case_number_loan_id");

                    b.HasIndex(new[] { "LoanId" }, "ix_litigations_loan_id")
                        .HasDatabaseName("ix_litigations_loan_id");

                    b.HasIndex(new[] { "LoanId" }, "ix_litigations_loan_id_guilty")
                        .IsUnique()
                        .HasDatabaseName("ix_litigations_loan_id_guilty")
                        .HasFilter("status = 'GUILTY'");

                    b.ToTable("litigations", null, t =>
                        {
                            t.HasCheckConstraint("ck_litigations_verdict_date_matches_status", "(status = 'PENDING') = (verdict_date IS NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
