// <auto-generated />
using System;
using CreditScore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditScore.Data.Migrations
{
    [DbContext(typeof(CreditScoreDbContext))]
    [Migration("20260929200649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditScore.Models.CreditScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveLoans")
                        .HasColumnType("integer")
                        .HasColumnName("active_loans");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CivilId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("civil_id");

                    b.Property<int>("Delinquencies")
                        .HasColumnType("integer")
                        .HasColumnName("delinquencies");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("grade");

                    b.Property<int>("LoansInLitigation")
                        .HasColumnType("integer")
                        .HasColumnName("loans_in_litigation");

                    b.Property<string>("PreviousGrade")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("previous_grade");

                    b.Property<int>("RecentGuiltyVerdicts")
                        .HasColumnType("integer")
                        .HasColumnName("recent_guilty_verdicts");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_credit_score_history");

                    b.HasIndex("CivilId", "CalculatedAt")
                        .HasDatabaseName("ix_credit_score_history_civil_id_calculated_at");

                    b.ToTable("credit_score_history", (string)null);
                });

            modelBuilder.Entity("CreditScore.Models.CustomerCreditScore", b =>
                {
                    b.Property<string>("CivilId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("civil_id");

                    b.Property<int>("ActiveLoans")
                        .HasColumnType("integer")
                        .HasColumnName("active_loans");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Delinquencies")
                        .HasColumnType("integer")
                        .HasColumnName("delinquencies");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("grade");

                    b.Property<int>("LoansInLitigation")
                        .HasColumnType("integer")
                        .HasColumnName("loans_in_litigation");

                    b.Property<int>("RecentGuiltyVerdicts")
                        .HasColumnType("integer")
                        .HasColumnName("recent_guilty_verdicts");

                    b.HasKey("CivilId")
                        .HasName("pk_credit_scores");

                    b.ToTable("credit_scores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
